"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 750

format = """
$directory\
$git_branch\
$git_status\
$conda\
$character\
"""

[directory]
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "bold yellow"

[conda]
symbol = " "
format = "[$symbol$environment]($style) "
style = "bold green"
ignore_base = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

